# Pinned GitHub Actions
# - actions/checkout v6.1.0 @ d23441a48e516b6c34aea4fa41551a30e30af803
#   - Repo: https://github.com/actions/checkout
#   - Version: https://github.com/actions/checkout/tree/v6.1.0
#   - Pinned: https://github.com/actions/checkout/commit/d23441a48e516b6c34aea4fa41551a30e30af803
# - pdm-project/setup-pdm v4.6 @ 544d7237314ee09c256785bd360f6b30add38b37
#   - Repo: https://github.com/pdm-project/setup-pdm
#   - Version: https://github.com/pdm-project/setup-pdm/tree/v4.6
#   - Pinned: https://github.com/pdm-project/setup-pdm/commit/544d7237314ee09c256785bd360f6b30add38b37

name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions to PyPI 📦
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
      - name: Set up PDM
        uses: pdm-project/setup-pdm@544d7237314ee09c256785bd360f6b30add38b37
        with:
          python-version: "3.12"
      - name: Build Exegol
        run: pdm build
      - name: Publish distribution 📦 to Test PyPI
        run: pdm publish --no-build --repository https://test.pypi.org/legacy/ --skip-existing
      - name: Publish distribution 📦 to PyPI (prod)
        run: pdm publish --no-build
